CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_GPIO_LOG_LEVEL_INF=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

# Don't compile the Azoteq driver at all (no DT instances are enabled).
CONFIG_INPUT_TPS43=n
CONFIG_I2C=n
